[project]
name = "recently"
version = "0.1.0"
description = "Quick little script to grab my most recent movies, books, and concerts."
readme= "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "feedparser>=6.0.11",
    "gspread>=6.2.1",
]